In [1]:
import numpy as np

In [2]:
a = np.array([1,3,4,5])
print(a)

[1 3 4 5]


In [5]:
import time
a = np.random.rand(10000)
b= np.random.rand(10000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("time taken:" + str(1000*(toc-tic))+" ms")

time taken:0.12326240539550781 ms


In [8]:
c = 0
tic = time.time()
for i in  range(10000):
  c == a[i]*b[i]
toc = time.time()
print("for time:"+str(1000*(toc-tic))+" ms")


for time:8.483171463012695 ms


#You can see time difference

#Broadcasting

In [10]:
import numpy as np

A = np.array([[45.0,23.0,34.0],
             [23.0,45.0,45.0]])
print(A)


[[45. 23. 34.]
 [23. 45. 45.]]


In [11]:
cal = A.sum(axis=0)

In [12]:
print(cal)

[68. 68. 79.]


In [13]:
percentage = 100 * A/cal.reshape(1,3)
print(percentage)

[[66.17647059 33.82352941 43.03797468]
 [33.82352941 66.17647059 56.96202532]]


In [14]:
cal_col = A.sum(axis=1)
print(cal_col)

[102. 113.]


In [15]:
percentage = 100 * A/cal_col.reshape(2,1)
print(percentage)

[[44.11764706 22.54901961 33.33333333]
 [20.3539823  39.82300885 39.82300885]]
